### ISSUE TITLE
ignoredPropertyPrefix

### ISSUE THREAD

**Issue by demoker** [com314159/RealmDeleteCascad#1]
```
+ (NSArray *) ignoredPropertyPrefix {
    return  @[@"NSInteger",@"NSString",@"NSDate",@"NSData",@"NSNumber",@"RLMObjectSchema",@"RLMRealm",
              @"B",
              @"c",
              @"d",
              @"i",
              @"f",
              @"l",
              @"s",
              @"I",
              @"q",
              ];
}
```

what is this?

**Comment by com314159** [comment]
this is the internal type, like NSInterger NSString

**Comment by com314159** [comment]
I remember char  I = NSInterger ,  you can try to print it.

**Comment by demoker** [comment]
Thank you for your reply！

**Comment by demoker** [comment]
But how to print? For example,thanks!

**Comment by com314159** [comment]
you can see the code in RunTimePropertyHelper, and you just add some NSLog to the code. When a class have a NSInteger property , you will get char 'i'.  there have document in apple.com, but I don't remember where it is.
